samples:
  CHM13_hifiasm:
    threads: 40
    assembler: hifiasm
    mem: 250GB
    data:
      ont:
        path: /project/logsdon_shared/data/reference/CHM13/raw_data/ont/
        include: ["*.fastq.gz"]
      hifi:
        path: /project/logsdon_shared/data/reference/CHM13/raw_data/hifi
        include: ["*.fastq.gz"]
  CHM13_verkko:
    threads: 40
    assembler: verkko
    mem: 250GB
    data:
      ont:
        path: /project/logsdon_shared/data/reference/CHM13/raw_data/ont/
        include: ["*.fastq.gz"]
      hifi:
        path: /project/logsdon_shared/data/reference/CHM13/raw_data/hifi
        include: ["*.fastq.gz"]
