samples:
  CHM13_hifiasm:
    threads: 40
    assembler: hifiasm
    mem: 250GB
    added_args: "-l0"
    data:
      ont:
        path: /project/logsdon_shared/data/reference/CHM13/raw_data/ont/
        # Filter to 100 kbp >
        include: ["*100kbp.fastq.gz"]
      hifi:
        path: /project/logsdon_shared/data/reference/CHM13/raw_data/hifi
        include: ["*.fastq.gz"]
  CHM13_verkko:
    threads: 40
    assembler: verkko
    mem: 250GB
    data:
      ont:
        path: /project/logsdon_shared/data/reference/CHM13/raw_data/ont/
        # Filter to 100 kbp >
        include: ["*100kbp.fastq.gz"]
      hifi:
        path: /project/logsdon_shared/data/reference/CHM13/raw_data/hifi
        # Gunzip due to bug in verkko
        include: ["*.fastq.gz.fastq"]
