[general]
log_level = "info"
bp_merge = 1
bp_wg_window = 5_000_000
bp_min_aln_length = 1
ignore_boundaries = true
merge_identical = true

[cov]
n_zscores_high = 4.0
n_zscores_low = 1.0
ratio_collapse = 2.0
ratio_false_dup = 0.5

[mapq]
n_zscores_low = 1.0
mapq_agg_fn = "Mean"

[mismatch]
n_zscores_high = 3.5
ratio_het = 0.2
rolling_mean_window = 11

[indel]
n_zscores_high = 3.5
min_ins_size = 2
min_del_size = 2
ratio_indel = 0.5
rolling_mean_window = 11

[softclip]
n_zscores_high = 3.5
ratio_softclip = 0.5

[group_by_ani]
window_size = 5_000
min_grp_size = 100_000
min_ident = 80.0

# [repeat]
# check_types = ["Misjoin", "Indel", "FalseDup"]
# ratio_repeat = 0.5
# bp_extend = 5

[minimum_size]
null = 1
collapse = 500
misjoin = 1
het_mismap = 1
mismatch = 1
false_dup = 2
softclip = 1
indel = 1
homopolymer = 1
dinucleotide = 1
simple_repeat = 1
other_repeat = 1
scaffold = 1
